services:
  - type: web
    name: heart-predict
    env: python
    region: oregon
    plan: free
    repo: https://github.com/komalbudakoti/heart-_prediction.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
